-- TransitOps AI: PostgreSQL production schema. Use UUIDs, foreign keys, and indexed operational fields.
CREATE TYPE user_role AS ENUM ('FLEET_MANAGER','DISPATCHER','SAFETY_OFFICER','FINANCIAL_ANALYST');
CREATE TYPE vehicle_status AS ENUM ('AVAILABLE','ON_TRIP','MAINTENANCE','RETIRED');
CREATE TYPE driver_status AS ENUM ('AVAILABLE','ON_TRIP','SUSPENDED','OFF_DUTY');
CREATE TYPE trip_status AS ENUM ('DRAFT','ASSIGNED','DISPATCHED','IN_TRANSIT','COMPLETED','CANCELLED');
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE TABLE users (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), email TEXT UNIQUE NOT NULL, password_hash TEXT NOT NULL, full_name TEXT NOT NULL, role user_role NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE vehicles (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), registration TEXT UNIQUE NOT NULL, name TEXT NOT NULL, type TEXT NOT NULL, capacity_kg INTEGER NOT NULL CHECK(capacity_kg > 0), fuel_type TEXT NOT NULL, odometer_km NUMERIC(12,1) NOT NULL DEFAULT 0, acquisition_cost NUMERIC(14,2), status vehicle_status NOT NULL DEFAULT 'AVAILABLE', insurance_expiry DATE, fitness_expiry DATE, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE drivers (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), full_name TEXT NOT NULL, email TEXT UNIQUE NOT NULL, phone TEXT NOT NULL, licence_number TEXT UNIQUE NOT NULL, licence_expiry DATE NOT NULL, safety_score NUMERIC(5,2) CHECK(safety_score BETWEEN 0 AND 100), status driver_status NOT NULL DEFAULT 'AVAILABLE', created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE trips (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), reference TEXT UNIQUE NOT NULL, source TEXT NOT NULL, destination TEXT NOT NULL, vehicle_id UUID NOT NULL REFERENCES vehicles(id), driver_id UUID NOT NULL REFERENCES drivers(id), cargo_weight_kg INTEGER NOT NULL CHECK(cargo_weight_kg > 0), distance_km NUMERIC(10,1) NOT NULL, revenue NUMERIC(14,2) NOT NULL, status trip_status NOT NULL DEFAULT 'DRAFT', departure_at TIMESTAMPTZ, arrival_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE maintenance_logs (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), vehicle_id UUID NOT NULL REFERENCES vehicles(id), category TEXT NOT NULL, cost NUMERIC(14,2) NOT NULL CHECK(cost >= 0), scheduled_for DATE NOT NULL, completed_at TIMESTAMPTZ, status TEXT NOT NULL, technician TEXT);
CREATE TABLE fuel_logs (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), vehicle_id UUID NOT NULL REFERENCES vehicles(id), driver_id UUID REFERENCES drivers(id), quantity_l NUMERIC(10,2) NOT NULL CHECK(quantity_l > 0), total_cost NUMERIC(14,2) NOT NULL, odometer_km NUMERIC(12,1) NOT NULL, logged_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE expenses (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), vehicle_id UUID REFERENCES vehicles(id), trip_id UUID REFERENCES trips(id), category TEXT NOT NULL, amount NUMERIC(14,2) NOT NULL CHECK(amount >= 0), expense_date DATE NOT NULL, notes TEXT);
CREATE TABLE notifications (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID REFERENCES users(id), level TEXT NOT NULL, title TEXT NOT NULL, body TEXT NOT NULL, read_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX trips_status_idx ON trips(status); CREATE INDEX trips_vehicle_id_idx ON trips(vehicle_id); CREATE INDEX maintenance_vehicle_date_idx ON maintenance_logs(vehicle_id, scheduled_for); CREATE INDEX fuel_vehicle_logged_idx ON fuel_logs(vehicle_id, logged_at);
